# run local build
# docker-compose up

# build certs for bot
# openssl req -newkey rsa:2048 -sha256 -nodes -keyout cert.key -x509 -days 365 -out cert.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"


version: '3'
services:
  rabbitmq:
    container_name: pigeomail-rmq
    image: rabbitmq:management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pg:
    image: bitnami/postgresql:15.3.0
    container_name: pigeomail-postgresql
    restart: always
    environment:
      POSTGRES_USER: pigeomail
      POSTGRES_PASSWORD: pigeomail
      POSTGRES_DB: pigeomail
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

