# run local build
# docker-compose up

# build certs for bot
# openssl req -newkey rsa:2048 -sha256 -nodes -keyout cert.key -x509 -days 365 -out cert.pem -subj "/C=US/ST=New York/L=Brooklyn/O=Example Brooklyn Company/CN=YOURDOMAIN.EXAMPLE"


version: '3'
services:
  rabbitmq:
    build:
      context: .
      dockerfile: RMQ.Dockerfile
    container_name: pigeomail-rabbitmq
    volumes:
      - ./.docker/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"

  pg:
    image: bitnami/postgresql:15.3.0
    container_name: pigeomail-postgresql
    restart: always
    environment:
      POSTGRES_USER: pigeomail
      POSTGRES_PASSWORD: pigeomail
      POSTGRES_DB: pigeomail
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/data/postgresql:/var/lib/postgresql/data

