// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: public-api.proto

package pigeomail_api_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PublicAPI_CreateTemporaryEMailV1_FullMethodName = "/pigeomail.PublicAPI/CreateTemporaryEMailV1"
)

// PublicAPIClient is the client API for PublicAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicAPIClient interface {
	CreateTemporaryEMailV1(ctx context.Context, in *PublicAPICreateTemporaryEMailV1Request, opts ...grpc.CallOption) (*PublicAPICreateTemporaryEMailV1Response, error)
}

type publicAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicAPIClient(cc grpc.ClientConnInterface) PublicAPIClient {
	return &publicAPIClient{cc}
}

func (c *publicAPIClient) CreateTemporaryEMailV1(ctx context.Context, in *PublicAPICreateTemporaryEMailV1Request, opts ...grpc.CallOption) (*PublicAPICreateTemporaryEMailV1Response, error) {
	out := new(PublicAPICreateTemporaryEMailV1Response)
	err := c.cc.Invoke(ctx, PublicAPI_CreateTemporaryEMailV1_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicAPIServer is the server API for PublicAPI service.
// All implementations should embed UnimplementedPublicAPIServer
// for forward compatibility
type PublicAPIServer interface {
	CreateTemporaryEMailV1(context.Context, *PublicAPICreateTemporaryEMailV1Request) (*PublicAPICreateTemporaryEMailV1Response, error)
}

// UnimplementedPublicAPIServer should be embedded to have forward compatible implementations.
type UnimplementedPublicAPIServer struct {
}

func (UnimplementedPublicAPIServer) CreateTemporaryEMailV1(context.Context, *PublicAPICreateTemporaryEMailV1Request) (*PublicAPICreateTemporaryEMailV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemporaryEMailV1 not implemented")
}

// UnsafePublicAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicAPIServer will
// result in compilation errors.
type UnsafePublicAPIServer interface {
	mustEmbedUnimplementedPublicAPIServer()
}

func RegisterPublicAPIServer(s grpc.ServiceRegistrar, srv PublicAPIServer) {
	s.RegisterService(&PublicAPI_ServiceDesc, srv)
}

func _PublicAPI_CreateTemporaryEMailV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicAPICreateTemporaryEMailV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAPIServer).CreateTemporaryEMailV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicAPI_CreateTemporaryEMailV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAPIServer).CreateTemporaryEMailV1(ctx, req.(*PublicAPICreateTemporaryEMailV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicAPI_ServiceDesc is the grpc.ServiceDesc for PublicAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pigeomail.PublicAPI",
	HandlerType: (*PublicAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemporaryEMailV1",
			Handler:    _PublicAPI_CreateTemporaryEMailV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public-api.proto",
}
