// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: public-api.proto

package pigeomail_api_pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicAPICreateTemporaryEMailV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublicAPICreateTemporaryEMailV1Request) Reset() {
	*x = PublicAPICreateTemporaryEMailV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicAPICreateTemporaryEMailV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAPICreateTemporaryEMailV1Request) ProtoMessage() {}

func (x *PublicAPICreateTemporaryEMailV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAPICreateTemporaryEMailV1Request.ProtoReflect.Descriptor instead.
func (*PublicAPICreateTemporaryEMailV1Request) Descriptor() ([]byte, []int) {
	return file_public_api_proto_rawDescGZIP(), []int{0}
}

type PublicAPICreateTemporaryEMailV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *PublicAPICreateTemporaryEMailV1Response) Reset() {
	*x = PublicAPICreateTemporaryEMailV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicAPICreateTemporaryEMailV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAPICreateTemporaryEMailV1Response) ProtoMessage() {}

func (x *PublicAPICreateTemporaryEMailV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAPICreateTemporaryEMailV1Response.ProtoReflect.Descriptor instead.
func (*PublicAPICreateTemporaryEMailV1Response) Descriptor() ([]byte, []int) {
	return file_public_api_proto_rawDescGZIP(), []int{1}
}

func (x *PublicAPICreateTemporaryEMailV1Response) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PublicAPIStreamEMailV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *PublicAPIStreamEMailV1Request) Reset() {
	*x = PublicAPIStreamEMailV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicAPIStreamEMailV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAPIStreamEMailV1Request) ProtoMessage() {}

func (x *PublicAPIStreamEMailV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAPIStreamEMailV1Request.ProtoReflect.Descriptor instead.
func (*PublicAPIStreamEMailV1Request) Descriptor() ([]byte, []int) {
	return file_public_api_proto_rawDescGZIP(), []int{2}
}

func (x *PublicAPIStreamEMailV1Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Subject   string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body      string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Sender    string `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient string `protobuf:"bytes,6,opt,name=recipient,proto3" json:"recipient,omitempty"`
	CreatedAt int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *EMail) Reset() {
	*x = EMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_public_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMail) ProtoMessage() {}

func (x *EMail) ProtoReflect() protoreflect.Message {
	mi := &file_public_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMail.ProtoReflect.Descriptor instead.
func (*EMail) Descriptor() ([]byte, []int) {
	return file_public_api_proto_rawDescGZIP(), []int{3}
}

func (x *EMail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EMail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EMail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EMail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EMail) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *EMail) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *EMail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_public_api_proto protoreflect.FileDescriptor

var file_public_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x70, 0x69, 0x67, 0x65, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x26, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x27, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41,
	0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72,
	0x79, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x35, 0x0a, 0x1d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x41, 0x50, 0x49, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0xb0, 0x01,
	0x0a, 0x05, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x32, 0xb3, 0x01, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x50, 0x49, 0x12, 0xa5,
	0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61,
	0x72, 0x79, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x56, 0x31, 0x12, 0x31, 0x2e, 0x70, 0x69, 0x67, 0x65,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x50, 0x49, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x45, 0x4d,
	0x61, 0x69, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x70,
	0x69, 0x67, 0x65, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41,
	0x50, 0x49, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72,
	0x79, 0x45, 0x4d, 0x61, 0x69, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x69, 0x67, 0x65, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x65, 0x6d, 0x6f, 0x66, 0x74, 0x68,
	0x65, 0x73, 0x6f, 0x75, 0x6c, 0x73, 0x2f, 0x70, 0x69, 0x67, 0x65, 0x6f, 0x6d, 0x61, 0x69, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x70, 0x69, 0x67, 0x65,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_public_api_proto_rawDescOnce sync.Once
	file_public_api_proto_rawDescData = file_public_api_proto_rawDesc
)

func file_public_api_proto_rawDescGZIP() []byte {
	file_public_api_proto_rawDescOnce.Do(func() {
		file_public_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_api_proto_rawDescData)
	})
	return file_public_api_proto_rawDescData
}

var file_public_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_public_api_proto_goTypes = []interface{}{
	(*PublicAPICreateTemporaryEMailV1Request)(nil),  // 0: pigeomail.PublicAPICreateTemporaryEMailV1Request
	(*PublicAPICreateTemporaryEMailV1Response)(nil), // 1: pigeomail.PublicAPICreateTemporaryEMailV1Response
	(*PublicAPIStreamEMailV1Request)(nil),           // 2: pigeomail.PublicAPIStreamEMailV1Request
	(*EMail)(nil),                                   // 3: pigeomail.EMail
}
var file_public_api_proto_depIdxs = []int32{
	0, // 0: pigeomail.PublicAPI.CreateTemporaryEMailV1:input_type -> pigeomail.PublicAPICreateTemporaryEMailV1Request
	1, // 1: pigeomail.PublicAPI.CreateTemporaryEMailV1:output_type -> pigeomail.PublicAPICreateTemporaryEMailV1Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_api_proto_init() }
func file_public_api_proto_init() {
	if File_public_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_public_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicAPICreateTemporaryEMailV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicAPICreateTemporaryEMailV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicAPIStreamEMailV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_public_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_api_proto_goTypes,
		DependencyIndexes: file_public_api_proto_depIdxs,
		MessageInfos:      file_public_api_proto_msgTypes,
	}.Build()
	File_public_api_proto = out.File
	file_public_api_proto_rawDesc = nil
	file_public_api_proto_goTypes = nil
	file_public_api_proto_depIdxs = nil
}
