// Code generated by protoc-gen-go-rmq (v1). DO NOT EDIT.

package pigeomailpb

import (
	"context"

	events1 "github.com/requiemofthesouls/pigeomail/api/pb"
	"github.com/requiemofthesouls/svc-rmq/client"
)

type PublisherEventsRMQClient interface {
	PaymentGatewayV1(ctx context.Context, ev *events1.EmptyMessage) error
}
type publisherEventsRMQClient struct {
	client client.Manager
}

func NewPublisherEventsRMQClient(client client.Manager) PublisherEventsRMQClient {
	return &publisherEventsRMQClient{
		client: client,
	}
}
func (c *publisherEventsRMQClient) PaymentGatewayV1(ctx context.Context, msg *events1.EmptyMessage) error {
	return c.client.PublishToExchange(ctx, "events.ps-list", "paymentGateway.v1", msg)
}
