// "github.com/requiemofthesouls/pigeomail/proto/rmq"
// Code generated by protoc-gen-go-rmq. DO NOT EDIT.

package pigeomailpb

import (
	"context"

	events1 "github.com/requiemofthesouls/pigeomail/api/pb"
	"github.com/requiemofthesouls/svc-rmq/server"
	"github.com/requiemofthesouls/svc-rmq/server/consumer"
)

type SMTPMessageEventsRMQServer interface {
	SMTPMessageReceivedV1(context.Context, *events1.EmptyMessage) error
}

func RegisterSMTPMessageEventsRMQServer(s server.Manager, srv SMTPMessageEventsRMQServer) {
	s.RegisterService(
		consumer.MapQueueHandlers{
			"h.ps-list.TransactionHandlerV1": consumer.QueueHandlerItem{
				ExchangeName: "events.payments",
				RoutingKey:   "transaction.v1",
				Handler:      NewRMQSMTPMessageReceivedV1(srv),
			},
		},
	)
}

type RMQSMTPMessageReceivedV1 struct {
	listener SMTPMessageEventsRMQServer
}

func NewRMQSMTPMessageReceivedV1(listener SMTPMessageEventsRMQServer) RMQSMTPMessageReceivedV1 {
	return RMQSMTPMessageReceivedV1{
		listener: listener,
	}
}
func (h RMQSMTPMessageReceivedV1) Handle(ctx context.Context, dec func(interface{}) error) error {
	var ev events1.EmptyMessage
	if err := dec(&ev); err != nil {
		return err
	}

	return h.listener.SMTPMessageReceivedV1(ctx, &ev)
}
